Home:
    resource: "Controllers\Home\Home"
    path: /
    actiondefault: build

Test:
    resource: "Controllers\Test\Test"
    path: /test
    actiondefault: build

SubscriberList:
    resource: "Controllers\SubscriberList\SubscriberList"
    path: /SubscriberList
    actiondefault: build

Subscribe:
    resource: "Controllers\Subscribe\Subscribe"
    path: /Subscribe
    actiondefault: build

Login:
    resource: "Controllers\login\login"
    path: /Login
    actiondefault: build

Register:
    resource: "Controllers\Register\Register"
    path: /Register
    actiondefault: build

Contact:
    resource: "Controllers\Contact\Contact"
    path: /Contact
    actiondefault: build

Logout:
    resource: "Controllers\logout\logout"
    path: /Logout
    actiondefault: build

PersonalArea:
    resource: "Controllers\personalArea\personalArea"
    path: /PersonalArea
    actiondefault: build