Home:
    resource: "Controllers\Home\Home"
    path: /
    actiondefault: build

Login:
    resource: "Controllers\\Login\\Login"
    path: /Login
    actiondefault: build

Register:
    resource: "Controllers\Register\Register"
    path: /Register
    actiondefault: build

Contact:
    resource: "Controllers\Contact\Contact"
    path: /Contact
    actiondefault: build

Logout:
    resource: "Controllers\\Logout\\Logout"
    path: /Logout
    actiondefault: build

PersonalArea:
    resource: "Controllers\\PersonalArea\\PersonalArea"
    path: /PersonalArea
    actiondefault: build

AccountVerification:
    resource: "Controllers\AccountVerification\AccountVerification"
    path: /AccountVerification
    actiondefault: build

LostPassword:
    resource: "Controllers\lostPassword\lostPassword"
    path: /LostPassword
    actiondefault: build

ChangePassword:
    resource: "Controllers\ChangePassword\ChangePassword"
    path: /ChangePassword
    actiondefault: build

ValidUser:
    resource: "Controllers\ValidUser\ValidUser"
    path: /validUser
    actiondefault: build
